- package.json
- src/app/_contexts/Player.context.tsx
- yarn.lock
Adds dependencies for MUI and a simple connection to the server.
> Add MUI dependencies

- src/app/_components/_sharedcomponents/Cards/CardTypes.ts
- src/app/_components/_sharedcomponents/Cards/GameCard/GameCard.tsx
- src/app/_components/_sharedcomponents/Cards/LeaderBaseCard/LeaderBaseCard.tsx
- src/app/_components/_sharedcomponents/LeaderBaseBoard/LeaderBase/LeaderBase.tsx
- src/app/_utils/s3Assets.ts
Adds support for card images from S3
> add card images

- src/app/_components/Gameboard/_subcomponents/Overlays/Prompts/BasicPrompt.tsx
- src/app/_components/Gameboard/_subcomponents/PlayerTray/CardActionTray.tsx
- Changed playerState to playerState.promptState since the stateObject was changed in the backend.
> #FE-promptStateFix

- src/app/_components/Gameboard/_subcomponents/UnitsBoard.tsx
- src/app/_components/HomePage/HomePagePlayMode.tsx
- src/app/_components/_sharedcomponents/CreateGameForm/CreateGameForm.tsx
- src/app/page.tsx
Frontend for starting custom games.
> Start test game

- src/app/_components/HomePage/HomePagePlayMode.tsx
Fixes the "Create Game" box to allow scrolling on small screens.
> fix create game scrollarea

- src/app/_components/QuickGame/FoundGame/FoundGame.tsx
- Fixed bug where when starting the game it would send mulitple gameStarts.
> #MultipleStartGameFix

- src/app/_components/Gameboard/_subcomponents/UnitsBoard.tsx
- src/app/_components/_sharedcomponents/Cards/GameCard/GameCard.tsx
- src/app/_contexts/Game.context.tsx
- src/app/_contexts/Popup.context.tsx
- src/app/lobby/page.tsx
Fixes some render issues with router references and game popups.
> UI fixes 11425

- src/app/_components/HomePage/HomePagePlayMode.tsx
- src/app/_components/Lobby/Deck/Deck.tsx
- src/app/_contexts/Game.context.tsx
Allow popups in private matches
> Private match fixes

- src/app/_components/Lobby/_subcomponents/SetUpCard/SetUpCard.tsx
- src/app/_components/_sharedcomponents/CreateGameForm/CreateGameForm.tsx
- src/app/_components/_sharedcomponents/QuickGameForm/QuickGameForm.tsx
- src/app/_utils/s3Utils.ts
- src/app/api/swudbdeck/route.ts
Changes in this PR:
1. Ability to load SWU stats decks
2. Add fallback error message for when someone tries to use a deck link for a site that's not supported
3. Clean up some Deck link documentation references that previously assumed swudb
> Load swu stats decks

- src/app/_components/Lobby/_subcomponents/SetUpCard/SetUpCard.tsx
- src/app/_components/_sharedcomponents/CreateGameForm/CreateGameForm.tsx
- src/app/_components/_sharedcomponents/QuickGameForm/QuickGameForm.tsx
- src/app/_utils/fetchDeckData.ts
- Refactored the way we send data to the backend. Currently we want to send both the reconstructed deck and the swuDB deck. So me and Veld can simultaneously work on the implementation.
> #DeckDataRefactor

- src/app/_components/Lobby/Deck/Deck.tsx
- src/app/_components/Lobby/SetUp/SetUp.tsx
- src/app/_components/Lobby/_subcomponents/SetUpCard/SetUpCard.tsx
- src/app/_components/_sharedcomponents/CreateGameForm/CreateGameForm.tsx
- src/app/_components/_sharedcomponents/QuickGameForm/QuickGameForm.tsx
- src/app/_contexts/Game.context.tsx
Lobby decks now sort by cost ascending. Added a slight hover effect to the "Exit Lobby" button.  Fixed a bug with set up component scrollbar not working.
> Add lobby deck sort

- src/app/_components/Gameboard/OpponentCardTray/OpponentCardTray.tsx
- src/app/_components/Gameboard/PlayerCardTray/PlayerCardTray.tsx
- src/app/_components/_sharedcomponents/Cards/LeaderBaseCard.tsx
Added initiative gamestate styling and removed leader space background color being incorrectly applied.
> Initiative gamestate styles

- src/app/_components/_sharedcomponents/Cards/GameCard.tsx
Adds preview to subcards:
https://github.com/user-attachments/assets/aff8c769-2542-4992-910a-59b56fc8567e
> Add Preview to Sub Cards

- src/app/api/swudbdeck/route.ts
- Edited the deck regex to work as currentbast does.
> swudb regex link change

- src/app/Navigation/NavBar.tsx
- src/app/Unimplemented/layout.tsx
- src/app/Unimplemented/page.tsx
- src/app/_components/_sharedcomponents/Cards/CardTypes.ts
- src/app/_components/_sharedcomponents/Cards/cardUtils.tsx
- src/app/_components/_sharedcomponents/ControlHub/ControlHub.tsx
- src/app/_utils/s3Utils.ts
- Added the unimplemented Page where we display all currently unimplemented cards.
> Che bato/unimplemented page

- src/app/_components/HomePage/HomePagePlayMode.tsx
- src/app/_components/HomePage/_subcomponents/JoinableGame/JoinableGame.tsx
- src/app/_components/Lobby/Deck/Deck.tsx
- src/app/_components/QuickGame/FoundGame/FoundGame.tsx
- src/app/_components/_sharedcomponents/CreateGameForm/CreateGameForm.tsx
- src/app/_components/_sharedcomponents/QuickGameForm/QuickGameForm.tsx
- src/app/_contexts/Game.context.tsx
- Made it so quickgames and public games are available to anon users. Some details could use a little polish.
> #Public games

- src/app/_components/HomePage/HomePageTypes.ts
- src/app/_components/HomePage/_subcomponents/GamesInProgress/GamesInProgress.tsx
- src/app/_components/HomePage/_subcomponents/PublicMatch/PublicMatch.tsx
- Got ongoing games ready for PR.
> #OngoingGames

- src/app/_components/Lobby/_subcomponents/SetUpCard/SetUpCard.tsx
- src/app/_components/_sharedcomponents/CreateGameForm/CreateGameForm.tsx
- src/app/_components/_sharedcomponents/QuickGameForm/QuickGameForm.tsx
- src/app/_utils/checkJson.ts
- Added additional validation steps so we don't have accept incorrect formats
- Changed that input fields now except texts
- Added json validation on FE so we know if the deck is correctly formated or not.
- Tested if the deck validation from BE correctly parses and responds.
> - Added the ability to import json as a decklink

- src/app/_components/Gameboard/OpponentCardTray/OpponentCardTray.tsx
- src/app/_components/_sharedcomponents/Popup/Popup.tsx
- src/app/_components/_sharedcomponents/Popup/Popup.types.ts
- src/app/_components/_sharedcomponents/Popup/PopupVariant/LeaveGamePopup.tsx
- src/app/_contexts/Popup.context.tsx
- Added popup for leaving the game.
> #156 Popup when leaving the game

- src/app/_components/Lobby/Deck/Deck.tsx
- src/app/_components/Lobby/_subcomponents/SetUpCard/SetUpCard.tsx
- We now display the correct value of minimum deck size and maximum sideboard.
> #DeckAndSideboardSize

- src/app/DeckPage/[DeckId]/page.tsx
- src/app/_components/Lobby/_subcomponents/SetUpCard/SetUpCard.tsx
- src/app/_components/_sharedcomponents/CreateGameForm/CreateGameForm.tsx
- src/app/_components/_sharedcomponents/DeckPage/AddDeckDialog.tsx
- src/app/_components/_sharedcomponents/QuickGameForm/QuickGameForm.tsx
- src/app/_utils/fetchDeckData.ts
Fixed bug where we didn't display the correct error when receiving a 403 from swudb.
> #403 unlisted error fix.

- src/app/_components/HomePage/HomePageTypes.ts
- src/app/_components/HomePage/_subcomponents/GamesInProgress/GamesInProgress.tsx
- src/app/_components/HomePage/_subcomponents/PublicMatch/PublicMatch.tsx
- src/app/_components/_sharedcomponents/Chat/Chat.tsx
removed spectate button  for private lobbies and chat for public
> #removeButtonAndChat

- next.config.mjs
- src/app/_utils/s3Utils.ts
- src/app/api/s3bucket/route.ts
Changes s3util to look for leaders in the base zone to append additional data for card images. All other cards will just use the set code.
> support new leader image format

- src/app/_components/Gameboard/_subcomponents/PlayerTray/DeckDiscard.tsx
- src/app/_components/Gameboard/_subcomponents/PlayerTray/Resources.tsx
Resource and discard zones will now be highlighted when there is a selectable card in that zone.
> Add selection border to resource/discard

- src/app/_components/_sharedcomponents/CreateGameForm/CreateGameForm.tsx
> update landing page deck list text

- src/app/_components/_sharedcomponents/Cards/CardValueAdjuster.tsx
- src/app/_components/_sharedcomponents/Cards/GameCard.tsx
- src/app/_components/_sharedcomponents/Cards/LeaderBaseCard.tsx
Added blue for distributing healing and red for damage. Need to change number background to an image and adjust colors for the +/- buttons.
> Add colors for distribution

- src/app/GameBoard/page.tsx
Add fix to remove central prompt border if there is no text e.g. spectator mode
> Remove border for spectator

- src/app/_contexts/Game.context.tsx
> #Attempting a fix for the connection issue.

- src/app/_components/_sharedcomponents/Cards/LeaderBaseCard.tsx
Fix for the damage counter images splitting
> Fix for the damage counter images splitting

- src/app/_components/Gameboard/OpponentCardTray/OpponentCardTray.tsx
- src/app/_components/_sharedcomponents/Preferences/PreferencesSubElementVariants/CurrentGameTab.tsx
- src/app/_components/_sharedcomponents/Preferences/_subComponents/BugReportDialog.tsx
- src/app/_components/_sharedcomponents/Preferences/_subComponents/PreferenceButton.tsx
- src/app/_contexts/Game.context.tsx
- src/app/_utils/s3Utils.ts
The BE PR has instructions how to set up the webhook on discord.
BE Pull request: https://github.com/SWU-Karabast/forceteki/pull/1057
There could be some positioning or perhaps styling changes.
> Che bato/bug reporting fe

- package-lock.json
- package.json
- src/app/_components/HomePage/News/News.tsx
**Chat Drawer & Chat UI Enhancements**
- Improved Responsiveness:
- Chat drawer width now uses min(20%, 280px) for better scaling on different screen sizes.
- Input containers and chat box styles use responsive paddings and minimum heights.
**Chat Header:**
- The chat drawer header now centers the "Chat" title and positions the chevron (close icon) consistently.
**Input Bar Usability:**
- Prevents sending blank or whitespace-only messages.
- The send icon in the chat input is smaller and does not crowd out the text, even on small screens.
- The chat input and placeholder text scale appropriately for different device sizes.
- Uses the new MUI slotProps.input.style API for input styling (avoiding deprecated inputProps).
**Message Display:**
- Player names are rendered as <span> with color …
> Chat drawer scaling improvements

- src/app/DeckPage/[DeckId]/page.tsx
- src/app/DeckPage/page.tsx
- src/app/_components/HomePage/_subcomponents/JoinableGame/JoinableGame.tsx
- src/app/_components/HomePage/_subcomponents/PublicMatch/PublicMatch.tsx
- src/app/_components/_sharedcomponents/CreateGameForm/CreateGameForm.tsx
- src/app/_components/_sharedcomponents/HomescreenWelcome/WelcomePopup.tsx
- src/app/_components/_sharedcomponents/Preferences/PreferencesSubElementVariants/GeneralTab.tsx
- src/app/_components/_sharedcomponents/QuickGameForm/QuickGameForm.tsx
- src/app/_contexts/User.context.tsx
- src/app/_contexts/UserTypes.ts
- src/app/_utils/DeckStorageUtils.ts
- src/app/api/auth/[...nextauth]/route.ts
Added user object to every API call so don't need to re-get the user details on the BE.
> #Added checks for the user object sent to the BE with each call

- src/app/_components/_sharedcomponents/Preferences/_subComponents/BugReportDialog.tsx
Warning -- we must merge https://github.com/SWU-Karabast/forceteki/pull/1183 first for the BackEnd to properly receive this message.  We can update the BE ahead of this branch and it will still work
Image of the new report (iphone12 in portrait mode)
> Added resolution and viewport to the error reporting

- src/app/_components/Gameboard/_subcomponents/PlayerTray/CardActionTray.tsx
- src/app/_components/_sharedcomponents/Popup/PopupVariant/DefaultPopup.tsx
- src/app/_components/_sharedcomponents/_styledcomponents/GradientBorderButton.tsx
Apply yellow style to pass button when resolving an ability.
> Add Pass Button Color for Abilities

- src/app/api/auth/[...nextauth]/route.ts
[- Added check for production for the domain-](https://github.com/SWU-Karabast/forceteki-client/issues/329)
Should make it easier to debug now in local.
> Add env var to control CORS origin for local testing

- src/app/DeckPage/[DeckId]/page.tsx
- src/app/DeckPage/page.tsx
- src/app/_utils/DeckStorageUtils.ts
Deck deletion now sticks with login.
BE PR
https://github.com/SWU-Karabast/forceteki/pull/1326
> #361 Deck deletion now sticks with login.

- src/app/DeckPage/page.tsx
- src/app/_components/Lobby/_subcomponents/SetUpCard/SetUpCard.tsx
- src/app/_components/_sharedcomponents/CreateGameForm/CreateGameForm.tsx
- src/app/_components/_sharedcomponents/HomescreenWelcome/WelcomePopup.tsx
- src/app/_components/_sharedcomponents/QuickGameForm/QuickGameForm.tsx
- src/app/_contexts/User.context.tsx
- src/app/_contexts/UserTypes.ts
- src/app/_utils/DeckStorageUtils.ts
- src/app/api/auth/[...nextauth]/route.ts
- src/next-auth.d.ts
- We now add the uuid of the user to the session and JWT token once we authorize them.
- We recreate and sign the JWT token when we update with the uuid.
BE PR:
https://github.com/SWU-Karabast/forceteki/pull/1406
> # Improved Token security and management.

- src/app/_components/_sharedcomponents/Chat/Chat.tsx
Adds chat styling to support this BE PR (can be merged independently): https://github.com/SWU-Karabast/forceteki/pull/1429
> Add chat styling for player ready / unready status messages

- src/app/_components/Lobby/_subcomponents/SetUpCard/SetUpCard.tsx
- src/app/_components/_sharedcomponents/QuickGameForm/QuickGameForm.tsx
Cleaning out some small notification text blocks we added to make people aware of the LoF stuff
> Remove LoF helper text from pages

- src/app/_components/HomePage/HomePagePlayMode.tsx
- src/app/_components/_sharedcomponents/HomescreenWelcome/UsernameChangeRequiredPopup.tsx
- src/app/_contexts/User.context.tsx
- src/app/_contexts/UserTypes.ts
- src/app/_utils/DeckStorageUtils.ts
FE logic for forcing a user to update their Username.
BE PR:
https://github.com/SWU-Karabast/forceteki/pull/1446
> # Added popup that forces the user to have to update their username.

- src/app/DeckPage/page.tsx
- src/app/api/swudbdeck/route.ts
Fixed cache issue that was causing players to see older versions of their decks
> # Fix Cache issue when retrieving decks.

- src/app/_components/_sharedcomponents/Preferences/_subComponents/EndGameOptionsQuickMatch.tsx
Grouped buttons for Quick Match Endgame Popup under one Actions header and renamed New Quick Match button to Requeue.
> Organize Quick Match Endgame Buttons

- src/app/_components/HomePage/_subcomponents/GamesInProgress/GamesInProgress.tsx
Add a ($ongoingGames) to the end of each leaders filter.
for #457
> add leader filter count
