src/app/ClientLayout.tsx
src/app/GameBoard/page.tsx
src/app/_components/Gameboard/GameboardTypes.ts
src/app/_components/Gameboard/OpponentCardTray/OpponentCardTray.tsx
src/app/_components/Gameboard/PlayerCardTray/PlayerCardTray.tsx
src/app/_components/Gameboard/_subcomponents/PlayerTray/DeckDiscard.tsx
src/app/_components/Gameboard/_subcomponents/UnitsBoard.tsx
src/app/_components/_sharedcomponents/Cards/CardTypes.ts
src/app/_components/_sharedcomponents/Cards/GameCard/GameCard.tsx
src/app/_components/_sharedcomponents/CreateGameForm/CreateGameForm.tsx
src/app/_components/_sharedcomponents/LeaderBaseBoard/LeaderBase/LeaderBase.tsx
src/app/_components/_sharedcomponents/LeaderBaseBoard/LeaderBaseBoard.tsx
src/app/_theme/theme.ts

Bit of cleanup to get the board more presentable and closer to the updated end state

Gameboard cleanup

---

src/app/_components/Gameboard/OpponentCardTray/OpponentCardTray.tsx
src/app/_components/Lobby/Players/Players.tsx
src/app/_components/QuickGame/FoundGame/FoundGame.tsx
src/app/_contexts/Game.context.tsx

- Added sendManualDisconnectMessage event so that we notify the server that this user is making a manualDisconnect.
- Added disabled = {true} to the leader & base cards since they were clickable in the lobby.
- Fixed bug with storedUnknownUserId when creating a private lobby the statement was written wrongly.
- Added SendManualDisconnectMessage function to notify the server when a user is making a manualDisconnect.

Che bato/manual disconnect

---

public/not-implemented.svg
src/app/_components/_sharedcomponents/Cards/CardTypes.ts
src/app/_components/_sharedcomponents/Cards/GameCard.tsx

Added logic to the Card that determines if a card has been implemented or not and gives the user a visual. Currently works in-game.
Something to note - in GameCard.tsx, line 29 sets isFaceUp = true but nowhere else does it confirm that to build the card. When testing, the "not implemented" styling weas applying to the opponent's cards in hand, but I was not able to figure out why that was the case. I would have assumed that checking isFaceUp was the fix, so I am not certain if this is some residual thing.

Added styling for cards that have not yet been implemented.

---

package-lock.json
package.json
src/app/GameBoard/page.tsx
src/app/_components/_sharedcomponents/CreateGameForm/CreateGameForm.tsx
src/app/_contexts/Game.context.tsx
src/app/_contexts/User.context.tsx

- Handles anonymous user assignment in the client to be passed to the back end for requests. 
- consolidates user login logic to assign and remove anonymous user properties when logins change.
There are a lot of change here to user login/persistence. We'll want to do a bit of manual testing to make sure that anonymous/logged in users can properly access their games and persist across refreshes. Logged in users use local storage so 2 logged in users still need to use incognito modes to simulate both users. Anonymous users use session storage which is unique for each tab so 2 anon users can use two tabs in the same browser.

Anonymous user support

---

src/app/_components/Gameboard/_subcomponents/UnitsBoard.tsx
src/app/_components/_sharedcomponents/Cards/CardTypes.ts
src/app/_components/_sharedcomponents/Cards/GameCard.tsx

- Added the capture mechanic to the FE with a divider on the units.
GameBoard -> finds capturedUnits and adds them to their corresponding card.
GameUnit -> Added basic styling and divider for captured units.

Che bato/capture mechanic

---

src/app/_components/_sharedcomponents/Cards/LeaderBaseCard.tsx

The leader area background no longer turns gray when the leader unit is exhausted

Fix leader background bug

---

src/app/_components/Gameboard/_subcomponents/PlayerTray/CardActionTray.tsx

Added support for the "disabled" property on buttons, which we use occasionally in the BE. Doing it now b/c it's a blocker for Give in to Your Anger.
Resolves #101

Support the `disabled` property on buttons

---

src/app/_components/Gameboard/_subcomponents/PlayerTray/CardActionTray.tsx

We were having an issue where multiple players were reporting that the "done" button at the resource stage pops up so fast that that they were accidentally double-tapping it after hitting "pass" to end the round.
Added a timer that disables the "done" button for 0.5s whenever a new resource phase happens to prevent this.

Disable done button for 0.5s on resource window

---

src/app/_components/Gameboard/Board/Board.tsx
src/app/_components/_sharedcomponents/Cards/LeaderBaseCard.tsx

Made some changes to the flex layout for the center column
- Leader / base card no longer cropped
- Cards scale down based on width and height (not just height)
- No more discrete levels (this is the controversial change)
- Gap inbetween the two bases will shrink if necessary

Center Column Scaling changes

---

src/app/_components/_sharedcomponents/Cards/CardValueAdjuster.tsx

restore the left-to-right layout of the value adjusters for spread damage

Bug fix for spread damage icons left to right ness

---

src/app/quickGame/page.tsx

Looks like the FE is potentially not transitioning correctly to the countdown screen if there is a disconnect right when the connection happens, possibly due to the lobby state getting dropped and then not listened for again.
Added some logic to check for it more aggressively, not 100% sure if this solves the issue but seems to help in some tests I tried.

Better handling for dropped lobby state

---

src/app/_components/Lobby/_subcomponents/SetUpCard/SetUpCard.tsx
src/app/_components/_sharedcomponents/QuickGameForm/QuickGameForm.tsx
src/app/_constants/mockData.ts

Now that we have force bases, we don't need to lean on the button anymore. Updates:
- Removed the Force base button but left a text notice there to let people know why it's gone (will remove in like a week)
- Enabled Next Set Preview in quick match mode with a text note that it's available (will remove in like a week)
- Updated the news article

Update LOF Next Set Preview format

---

src/app/_components/_sharedcomponents/Cards/GameCard.tsx

- Clears upgrade popup on click when it is selectable. This might introduce a popup flicker in cases where you are not selecting the upgrade for defeat but defeating an upgrade is what we're doing majority of the time when they are selectable so I think this is a fine tradeoff. 
- Update mouse styling when hovering subcards
- Remove aria warnings in console related to hover popups

clear upgrade popup on click

---

src/app/_components/_sharedcomponents/Cards/CardTypes.ts
src/app/_components/_sharedcomponents/Popup/PopupVariant/SelectCardsPopup.tsx

Thrawn1 leader now shows text under card for ability popup to determine whose deck each card is on top of.

Add Text to Ability Prompt

---

src/app/_components/HomePage/HomePageTypes.ts
src/app/_components/HomePage/_subcomponents/NewsItem/NewsItem.tsx
src/app/_constants/mockData.ts

People were trying to click on the image showing the login buttons on the announcement, adding a link to that button so it will redirect them to the login page

Make login announcement image into a link

---

src/app/_components/_sharedcomponents/Preferences/PreferencesSubElementVariants/CurrentGameTab.tsx

I've noticed that bug report logs often show that the player had very little time left before being kicked for inactivity, added support for the FE to send an action timer reset request when the player opens the bug report dialog. BE PR link: https://github.com/SWU-Karabast/forceteki/pull/1506

Extend action timer when bug report dialog opens

---

src/app/_components/_sharedcomponents/Cards/CardTypes.ts
src/app/_components/_sharedcomponents/Cards/GameCard.tsx

We're generalizing the "hidden" icon to represent anything that can't be targeted for an attack due to an effect. The FE property was renamed, see BE PR here: https://github.com/SWU-Karabast/forceteki/pull/1508

Add support for renamed hidden icon

---

src/app/_components/_sharedcomponents/DeckPage/AddDeckDialog.tsx

Pretty straightforward, copied the text from the home screen section to add a deck and then pasted it into the welcome modal. Only note is that if desired I can change is that I removed the input placeholder now that it isn't just a SWUDB link.

Copy Text from Homepage to Decks Modal

---

src/app/_components/HomePage/HomePagePlayMode.tsx
src/app/_components/Lobby/_subcomponents/SetUpCard/SetUpCard.tsx
src/app/_components/_sharedcomponents/ControlHub/ControlHub.tsx
src/app/_components/_sharedcomponents/CreateGameForm/CreateGameForm.tsx
src/app/_components/_sharedcomponents/QuickGameForm/QuickGameForm.tsx
src/app/_contexts/User.context.tsx
src/app/_contexts/UserTypes.ts
src/app/api/swustats/route.ts

The selected deck from the saved decks dropdown was not persisting across refreshes if a user is logged in. This ended up being an issue with the context thrashing a bit while the user loads.
Fixed the issue and hit a few other small improvements:
- Consolidated the remaining duplicated code from the tabs up to HomePagePlayMode
- Removed some debug console logs from previous PRs
- Removed the "old karabast" link as suggested by ninin and Oot
- Updated the new deck / saved deck radio button to default to "saved deck" on first load if saved decks are available

Fix deck selection dropdown memory for logged-in users

---

src/app/_utils/s3Utils.ts

Updated s3Utils to pull a standard or truncated version of the token cards.  Used Mobyus's cards to create a stitched version for the game cards that have a bottom border
Two examples with hover on the token
New s3 directory structure for tokens:
standard: what we were currently using
truncated: the new truncated images (using the same python scripts)
custom: "resized" images using the python script from Mobyus's contributions in the channel

Updated the token cards to stitch the bottom border in their truncated form
